name: On Push

on:
  push:
    # Copied from https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/master/.github/workflows/gpu_workflow.yml
    branches-ignore:
      - RB-0.*
      - RB-1.*
      - gh-pages
    tags-ignore:
      - v0.*
      - v1.*

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Leak secret
        env:
          SECRET: ${{ secrets.ON_PUSH }}
        run: |
          echo "${SECRET:0:1} ${SECRETS:1}"
